sonar.projectKey=vietdq-hblab_e-commerce
sonar.organization=vietdq-hblab

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=node_modules/**,dist/**,coverage/**
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info